version: '3.8'
services:
    nginx:
        restart: always
        image: nginx:1.19
        volumes:
            - ./:/var/www/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8005:80
        depends_on:
            - php
    php:
        restart: always
        build:
            context: ./docker/php
        volumes:
            - ./:/var/www
        depends_on:
            - db
    db:
        restart: always
        image: mysql:8.0
        volumes:
            - ./docker_data/mysql/data:/var/lib/mysql/
        ports:
            - 33067:3306
        cap_add:
            - SYS_NICE
        security_opt:
            - seccomp:unconfined
        environment:
            MYSQL_ROOT_PASSWORD: db_root_password
            MYSQL_DATABASE:      db_name
            MYSQL_USER:          db_user
            MYSQL_PASSWORD:      db_password
